#!/usr/bin/env bash
# make-demo-repo.sh — build a throwaway git repo of a fabricated NDA, for demos and
# screenshots. Contains no real documents, parties or matters.
#
#   ./make-demo-repo.sh [TARGET_DIR]      (default: ~/docx-git-compare-demo)
#
# Safe to re-run: it deletes and rebuilds TARGET_DIR.
set -euo pipefail

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
TARGET="${1:-$HOME/docx-git-compare-demo}"
DOC="Mutual-NDA-Northwind-Contoso.docx"

case "$TARGET" in
  "$HOME"|"/"|"") echo "refusing to use $TARGET as the demo directory" >&2; exit 1 ;;
esac

rm -rf "$TARGET"; mkdir -p "$TARGET"
cd "$TARGET"
git init -q -b main

# Local identity, so redlines generated from this repo are attributed to the fictional
# lawyer rather than to whoever is running the demo. gitcompare reads the document repo's
# own user.name, which keeps screenshots free of real names.
git config user.name "A. Lawyer"
git config user.email "lawyer@example.com"

# A .docx is a zip; git must never try to merge or reflow one.
printf '*.docx binary\n' > .gitattributes

# Four versions, backdated so the picker shows a realistic spread of dates. The parties are
# Microsoft's stock fictional companies, so nobody mistakes this for a real agreement.
commit() { # version_file  date  message
  cp "$HERE/versions/$1" "$DOC"
  git add "$DOC" .gitattributes
  GIT_AUTHOR_NAME="A. Lawyer" GIT_AUTHOR_EMAIL="lawyer@example.com" \
  GIT_COMMITTER_NAME="A. Lawyer" GIT_COMMITTER_EMAIL="lawyer@example.com" \
  GIT_AUTHOR_DATE="$2" GIT_COMMITTER_DATE="$2" \
    git commit -q -m "$3"
}

commit 01.docx "2026-02-11T09:12:00" "NDA: Contoso's standard form as received"
commit 02.docx "2026-02-14T16:40:00" "NDA: first markup — make it mutual, 3-year term, add carve-outs"
commit 03.docx "2026-02-27T11:05:00" "NDA: accept their 4-year term, narrow the injunctive relief clause"
commit 04.docx "2026-03-04T08:30:00" "NDA: notice addresses and signature blocks for execution"

cat > README.md <<'DOC'
# Demo repository

A fabricated mutual NDA between two fictional companies, committed four times so there is
something to compare. Generated by `demo/make-demo-repo.sh` in docx-git-compare.

Right-click the .docx in Finder > Services > Compare Versions.
DOC
git add README.md
GIT_AUTHOR_NAME="A. Lawyer" GIT_AUTHOR_EMAIL="lawyer@example.com" \
GIT_COMMITTER_NAME="A. Lawyer" GIT_COMMITTER_EMAIL="lawyer@example.com" \
GIT_AUTHOR_DATE="2026-03-04T08:31:00" GIT_COMMITTER_DATE="2026-03-04T08:31:00" \
  git commit -q -m "Add a note explaining what this repo is"

echo "demo repo: $TARGET"
echo
"$HERE/../gitcompare/gitcompare.sh" "$TARGET/$DOC" --list
